version: '3'

services:
  db:
    image: postgres:14.2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      LANG: ja_JP.utf8
      LC_ALL: en_US.utf-8
    working_dir: /workspace

volumes:
  postgres-data:
