version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ../
        target: /workspace
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      LANG: ja_JP.utf8
      LC_ALL: en_US.utf-8

volumes:
  postgres-data:
